group: playschool_bbh_fewshot
task:
  - playschool_bbh_fewshot_boolean_expressions
  - playschool_bbh_fewshot_causal_judgement
  - playschool_bbh_fewshot_date_understanding
  - playschool_bbh_fewshot_disambiguation_qa
  - playschool_bbh_fewshot_dyck_languages
  - playschool_bbh_fewshot_formal_fallacies
  - playschool_bbh_fewshot_geometric_shapes
  - playschool_bbh_fewshot_hyperbaton
  - playschool_bbh_fewshot_logical_deduction_five_objects
  - playschool_bbh_fewshot_logical_deduction_seven_objects
  - playschool_bbh_fewshot_logical_deduction_three_objects
  - playschool_bbh_fewshot_movie_recommendation
  - playschool_bbh_fewshot_multistep_arithmetic_two
  - playschool_bbh_fewshot_navigate
  - playschool_bbh_fewshot_object_counting
  - playschool_bbh_fewshot_penguins_in_a_table
  - playschool_bbh_fewshot_reasoning_about_colored_objects
  - playschool_bbh_fewshot_ruin_names
  - playschool_bbh_fewshot_salient_translation_error_detection
  - playschool_bbh_fewshot_snarks
  - playschool_bbh_fewshot_sports_understanding
  - playschool_bbh_fewshot_temporal_sequences
  - playschool_bbh_fewshot_tracking_shuffled_objects_five_objects
  - playschool_bbh_fewshot_tracking_shuffled_objects_seven_objects
  - playschool_bbh_fewshot_tracking_shuffled_objects_three_objects
  - playschool_bbh_fewshot_web_of_lies
  - playschool_bbh_fewshot_word_sorting
aggregate_metric_list:
  - metric: exact_match
    aggregation: mean
    weight_by_size: true
metadata:
  version: 3.0
