task: playschool_ifeval
dataset_path: google/IFEval
output_type: generate_until
test_split: train
doc_to_text: prompt
doc_to_target: instruction_id_list
generation_kwargs:
  until: []
  do_sample: false
  temperature: 0.0
  max_gen_toks: 1280
process_results: utils.process_results
metric_list:
  - metric: prompt_level_strict_acc
    aggregation: mean
    higher_is_better: true
  - metric: inst_level_strict_acc
    aggregation: utils.agg_inst_level_acc
    higher_is_better: true
  - metric: prompt_level_loose_acc
    aggregation: mean
    higher_is_better: true
  - metric: inst_level_loose_acc
    aggregation: utils.agg_inst_level_acc
    higher_is_better: true
metadata:
  version: 4.0
